version: '3'

networks:
  backend: 
    driver: overlay

services: 
  db:
    image: colinmollenhour/mariadb-galera-swarm
    #build: 
    #  context: galera
    #  args:
    #    MYSQL_ROOT_PASSWORD: s3cr3t
    environment:
      - XTRABACKUP_PASSWORD=s3cr3t
      - CLUSTER_NAME=db
      - MYSQL_ROOT_PASSWORD=s3cr3t
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=r3dmin3
      - GCOMM_MINIMUM=2
    networks:
      - backend
    depends_on:
      - galera-seed
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    stop_grace_period: 30s
    command: node tasks.galera-seed,tasks.db
