version: '3'

networks:
  backend: 
    driver: overlay

volumes:
  # persistent volume for mysql databases
  mysql_data:

services: 
  db:
    # use mysql 5 image from docker hub
    image: mysql:5
    # setup mysql environment
    # see https://hub.docker.com/_/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=s3cr3t
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=redmine
    networks:
      - backend
    # use persinstent volume for DBs
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == birthday1
    stop_grace_period: 30s
