version: '3'

networks:
  backend: 
    driver: overlay

services: 
  galera-seed:
    image: mariadb-galera-swarm:1.0
    build: 
      context: galera
      args:
        MYSQL_ROOT_PASSWORD: s3cr3t
    environment:
      - XTRABACKUP_PASSWORD=s3cr3t
      - CLUSTER_NAME=db
      - MYSQL_ROOT_PASSWORD=s3cr3t
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=r3dmin3
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == birthday1
    stop_grace_period: 30s
    command: seed
